# Site settings
title: 잉꼬 - 잔여 포인트의 합리적인 소비
email: LeroyKim92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/inco" # the subpath of your site, e.g. /blog/
url: "https://sterkdev.github.io" # the base hostname & protocol for your site

# User setting
owner: Start Bootstrap
email: LeroyKim92@gmail.com
facebook_username: 
twitter_username: 
github_username: 
address:
  - line: 대구광역시 북구 대학로 80
  - line: 경북대학교 정보전산원 110호
  # Feel free to add more lines here 
telephone: (123) 456-7890
copyright: Your Site

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown
